# Sätt Perl att hitta cgi-lib.pl, common.pl, schema.pl via relativa require
SetEnv PERL5LIB /usr/lib/cgi-bin/val98

# Skicka besökare på rot-URL:en vidare till Väljarkompassens startsida
RedirectMatch ^/$ /cgi-bin/val98/valguide.pl
